name: main

on: [push, pull_request]

jobs:
  tests:
    name: Run tests for (${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "2.7", "3.0", "3.1", "3.2", "3.3" ]
        rails: [ "6.1", "7.0", "7.1" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gems
        run: |
          gem install bundler
          bundle install
          bundle exec appraisal install --jobs 4 --retry 3
      - name: Run test
        env:
          MATRIX_RAILS_VERSION: ${{ matrix.rails }}
        run: bundle exec appraisal rails-${MATRIX_RAILS_VERSION} rake test
